apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: php-frontend
spec:
  ports:
  - port: 9000
  selector:
    app: frontend
    tier: php-frontend
  clusterIP: None
