apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: web-frontend
spec:
  ports:
  - port: 80
  selector:
    app: frontend
    tier: web-frontend
  clusterIP: None
