apiVersion: v1
data:
  groups.sql: |
    -- phpMyAdmin SQL Dump
    -- version 4.5.4.1deb2ubuntu1
    -- http://www.phpmyadmin.net
    --

    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    SET time_zone = "+00:00";


    /*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
    /*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
    /*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
    /*!40101 SET NAMES utf8mb4 */;

    --
    -- Database: `groups`
    --

    -- --------------------------------------------------------

    --
    -- Table structure for table `user`
    --

    CREATE TABLE `group` (
      `id` int(11) NOT NULL,
      `name` varchar(255) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

    --
    -- Dumping data for table `group`
    --

    INSERT INTO `group` (`id`, `name`) VALUES
    (1, 'Compras'),
    (2, 'Finanzas'),
    (3, 'Viajes'),
    (4, 'Ventas'),
    (5, 'Adminsitracion');

    --
    -- Indexes for dumped tables
    --

    --
    -- Indexes for table `group`
    --
    ALTER TABLE `group`
      ADD PRIMARY KEY (`id`),
      ADD UNIQUE KEY `name` (`name`);

    --
    -- AUTO_INCREMENT for dumped tables
    --

    --
    -- AUTO_INCREMENT for table `group`
    --
    ALTER TABLE `group`
      MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
    /*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
    /*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
    /*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dump-group
