# Fichero de creación de servicio MySQL para el MS de grupos
apiVersion: v1
kind: Service
metadata:
  name: mysql-back-groups
  labels:
    app: back-groups
spec:
  ports:
    - port: 3306
  selector:
    app: back-groups
    tier: mysql-back-groups
  clusterIP: None
