apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: back-users
  name: php-back-users
spec:
  ports:
  - port: 9000
  selector:
    app: back-users
    tier: php-back-users
  clusterIP: None
