# Fichero de Deployment de Apache
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-back-users
  labels:
    app: back-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-users
      tier: web-back-users
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: back-users
        tier: web-back-users
    spec:
      containers:
      - image: mmiguel80/web-back-users:v1.1
        name: web-back-users
        resources:
          requests:
            memory: "64Mi"
            cpu: "80m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10  
        ports:
        - containerPort: 80
          name: web-back-users  