apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: back-users
  name: web-back-users
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: back-users
    tier: web-back-users
  clusterIP: None
